"""empty message

Revision ID: 29eb3a9c04bd
Revises: 
Create Date: 2020-05-18 08:52:17.033984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29eb3a9c04bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dormitory',
    sa.Column('dormitoryId', sa.Integer(), nullable=False),
    sa.Column('dormitoryName', sa.String(length=100), nullable=True),
    sa.Column('dormitoryNumber', sa.String(length=100), nullable=True),
    sa.Column('dormitoryManager', sa.String(length=100), nullable=True),
    sa.Column('member1', sa.String(length=100), nullable=True),
    sa.Column('member2', sa.String(length=100), nullable=True),
    sa.Column('member3', sa.String(length=100), nullable=True),
    sa.Column('member4', sa.String(length=100), nullable=True),
    sa.Column('innerTemperature', sa.String(length=100), nullable=True),
    sa.Column('innerHumidity', sa.String(length=100), nullable=True),
    sa.Column('remainWater', sa.Integer(), nullable=True),
    sa.Column('remainLight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('dormitoryId')
    )
    op.create_table('log',
    sa.Column('logId', sa.Integer(), nullable=False),
    sa.Column('logTime', sa.String(length=100), nullable=True),
    sa.Column('logPerson', sa.String(length=100), nullable=True),
    sa.Column('logSource', sa.String(length=200), nullable=True),
    sa.Column('isIn', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('logId')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('roomId', sa.Integer(), nullable=True),
    sa.Column('roomname', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('myclass', sa.String(length=100), nullable=True),
    sa.Column('roommate1', sa.String(length=100), nullable=True),
    sa.Column('roommate2', sa.String(length=100), nullable=True),
    sa.Column('roommate3', sa.String(length=100), nullable=True),
    sa.Column('introduction', sa.String(length=100), nullable=True),
    sa.Column('userPicture', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('log')
    op.drop_table('dormitory')
    # ### end Alembic commands ###
