"""empty message

Revision ID: aa4a37f39a20
Revises: 
Create Date: 2020-04-14 17:55:11.909744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4a37f39a20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('dormitoryId', sa.Integer(), nullable=False),
    sa.Column('dormitoryName', sa.String(length=100), nullable=True),
    sa.Column('dormitoryNumber', sa.String(length=100), nullable=True),
    sa.Column('docmitoryManager', sa.String(length=100), nullable=True),
    sa.Column('innerTemperature', sa.String(length=100), nullable=True),
    sa.Column('innerHumidity', sa.String(length=100), nullable=True),
    sa.Column('outerTemperature', sa.String(length=100), nullable=True),
    sa.Column('outerHumidity', sa.String(length=100), nullable=True),
    sa.Column('remainWater', sa.Integer(), nullable=True),
    sa.Column('remainLight', sa.Integer(), nullable=True),
    sa.Column('remainWaterFee', sa.Integer(), nullable=True),
    sa.Column('remainLightFee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('dormitoryId')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('roomId', sa.Integer(), nullable=True),
    sa.Column('roomname', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('myclass', sa.String(length=100), nullable=True),
    sa.Column('roommate1', sa.String(length=100), nullable=True),
    sa.Column('roommate2', sa.String(length=100), nullable=True),
    sa.Column('roommate3', sa.String(length=100), nullable=True),
    sa.Column('introduction', sa.String(length=100), nullable=True),
    sa.Column('userPicture', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('room')
    # ### end Alembic commands ###
